2025-05-08 12:28:20 - root - INFO - Logging enabled to file: scanner.log
2025-05-08 12:28:20 - __main__ - INFO - Initializing SQL Injection Scanner...
2025-05-08 12:28:20 - __main__ - INFO - Loaded 37 unique payloads from data/payloads.txt
2025-05-08 12:28:20 - __main__ - INFO - Attempting login to http://localhost:8000/process.php with method POST
2025-05-08 12:28:20 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /process.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0d97f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:28:21 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /process.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0d9a90>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:28:22 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /process.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0d9b80>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:28:22 - __main__ - WARNING - Login request to http://localhost:8000/process.php failed (no response).
2025-05-08 12:28:22 - __main__ - INFO - Scanner initialized. Base scan URL set to: http://localhost:8000/
2025-05-08 12:28:22 - __main__ - INFO - Starting discovery from base: http://localhost:8000/ using wordlist: data/common_paths.txt
2025-05-08 12:28:22 - __main__ - INFO - Generated 228 potential targets for discovery.
2025-05-08 12:28:22 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0da930>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:28:23 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0dae40>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:28:24 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0db0e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:28:24 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0dab10>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:28:25 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0daa80>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:28:26 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0da000>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:28:26 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0d98e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:28:27 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0db230>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:28:28 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0db860>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:28:28 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0dbb00>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:28:29 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0d9670>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:28:30 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0e83b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:28:30 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0e87a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:28:31 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0e8b90>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:28:32 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0e8f20>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:28:32 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0e9640>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:28:33 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0dbf20>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:28:34 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0dbd10>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:28:34 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0db5f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:28:35 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0d9790>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:28:36 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0d9d90>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:28:36 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0d9b80>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:28:37 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0dad80>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:28:38 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0e9040>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:28:38 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0e8e60>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:28:39 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0e8740>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:28:40 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0e8500>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:28:40 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0e9790>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:28:41 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0e9cd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:28:42 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0dac90>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:28:42 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0da8d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:28:43 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0d9cd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:28:44 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0db410>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:28:44 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0db7a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:28:45 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0dbb60>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:28:46 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0e9dc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:28:46 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0e8050>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:28:47 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0e8920>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:28:48 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0e8d10>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:28:48 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0e8ec0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:28:49 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0ea0f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:28:50 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0ea120>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:28:50 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0dba70>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:28:51 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0dbc80>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:28:52 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0db680>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:28:52 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0d9790>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:28:53 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0d9a90>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:28:54 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0dab70>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:28:54 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0da9c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:28:55 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0ea3f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:28:56 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0e8c20>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:28:56 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0e8ad0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:28:57 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0e8740>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:28:58 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0e8a10>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:28:58 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0ea750>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:28:59 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0daed0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:29:00 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0dacc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:29:00 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0da000>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:29:01 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0d98e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:29:02 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0dad80>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:29:02 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0dbef0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:29:03 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0dbb90>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:29:04 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0e8bf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:29:04 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0ea2a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:29:05 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0e82f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:29:06 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0e8860>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:29:06 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0e8f80>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:29:07 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0ea420>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:29:08 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0dad20>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:29:08 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0dba70>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:29:09 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0dbd10>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:29:10 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0db470>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:29:10 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0db440>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:29:11 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71608d0d8c50>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:29:29 - root - INFO - Logging enabled to file: scanner.log
2025-05-08 12:29:29 - __main__ - INFO - Initializing SQL Injection Scanner...
2025-05-08 12:29:29 - __main__ - INFO - Loaded 37 unique payloads from data/payloads.txt
2025-05-08 12:29:29 - __main__ - INFO - Attempting login to http://localhost:8000/process.php with method POST
2025-05-08 12:29:29 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /process.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7b3aaf4f7b00>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:29:30 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /process.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7b3aad3c5e80>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:29:31 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /process.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7b3aad3c6210>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:29:31 - __main__ - WARNING - Login request to http://localhost:8000/process.php failed (no response).
2025-05-08 12:29:31 - __main__ - INFO - Scanner initialized. Base scan URL set to: http://localhost:8000/
2025-05-08 12:29:31 - __main__ - INFO - Starting discovery from base: http://localhost:8000/ using wordlist: data/common_paths.txt
2025-05-08 12:29:31 - __main__ - INFO - Generated 228 potential targets for discovery.
2025-05-08 12:29:31 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7b3aad3c6d80>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:29:32 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7b3aad3c7230>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:29:33 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7b3aad3c63f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:29:33 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7b3aad3c7560>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:29:34 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7b3aad3c6e70>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:29:35 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7b3aad3c63c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:29:35 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7b3aad3c6000>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:29:36 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7b3aad3c7710>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:29:37 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7b3aad3c7da0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:29:37 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7b3aad3c7fb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:29:38 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7b3aad3e8290>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:29:39 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7b3aad3e8770>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:29:39 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7b3aad3e8ad0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:29:49 - root - INFO - Logging enabled to file: scanner.log
2025-05-08 12:29:49 - __main__ - INFO - Initializing SQL Injection Scanner...
2025-05-08 12:29:49 - __main__ - INFO - Loaded 37 unique payloads from data/payloads.txt
2025-05-08 12:29:49 - __main__ - INFO - Attempting login to http://localhost:8000/process.php with method POST
2025-05-08 12:29:49 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /process.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x77d787bfd4c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:29:50 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /process.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x77d787bfd6d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:29:51 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /process.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x77d787bfdc10>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:29:51 - __main__ - WARNING - Login request to http://localhost:8000/process.php failed (no response).
2025-05-08 12:29:51 - __main__ - INFO - Scanner initialized. Base scan URL set to: http://localhost:8000/
2025-05-08 12:29:51 - __main__ - INFO - Starting discovery from base: http://localhost:8000/ using wordlist: data/common_paths.txt
2025-05-08 12:29:51 - __main__ - INFO - Generated 228 potential targets for discovery.
2025-05-08 12:29:51 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x77d787bfe600>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:29:52 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x77d787bfe8d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:03 - root - INFO - Logging enabled to file: scanner.log
2025-05-08 12:30:03 - __main__ - INFO - Initializing SQL Injection Scanner...
2025-05-08 12:30:03 - __main__ - INFO - Loaded 37 unique payloads from data/payloads.txt
2025-05-08 12:30:03 - __main__ - INFO - Attempting login to http://localhost:8000/process.php with method POST
2025-05-08 12:30:03 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /process.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde0290>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:04 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /process.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde12b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:05 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /process.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde14f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:05 - __main__ - WARNING - Login request to http://localhost:8000/process.php failed (no response).
2025-05-08 12:30:05 - __main__ - INFO - Scanner initialized. Base scan URL set to: http://localhost:8000/
2025-05-08 12:30:05 - __main__ - INFO - Starting discovery from base: http://localhost:8000/ using wordlist: data/common_paths.txt
2025-05-08 12:30:05 - __main__ - INFO - Generated 228 potential targets for discovery.
2025-05-08 12:30:05 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde1ee0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:06 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde25a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:07 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde2870>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:07 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde24e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:08 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde2000>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:09 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde14f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:09 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde13d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:10 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde2ba0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:11 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde2d50>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:11 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde3380>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:12 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde3800>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:13 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde3b00>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:13 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde3d40>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:14 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde8350>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:15 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde8800>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:15 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde8d70>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:16 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde3c80>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:17 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde3b60>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:17 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde3770>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:18 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde28d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:19 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde2b70>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:19 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde0ce0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:20 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde16d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:21 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde1460>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:21 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde2300>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:22 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde89e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:23 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde8470>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:23 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde8ec0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:24 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde9400>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:25 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde2300>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:25 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde14f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:26 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde0fe0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:27 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde0680>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:27 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde2d50>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:28 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde3410>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:29 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde35f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:29 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde3c80>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:30 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde83e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:31 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde8200>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:31 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde84a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:32 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde9820>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:33 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde9850>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:33 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde3c80>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:34 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde3710>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:35 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde2bd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:35 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde0ec0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:36 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde2570>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:37 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde0ce0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:37 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde1af0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:38 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde2210>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:39 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde9b50>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:39 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde9760>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:40 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde89e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:41 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde8e90>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:41 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde9e80>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:42 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde2450>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:43 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde14f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:43 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde1100>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:44 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde1280>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:45 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde11f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:45 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde3860>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:46 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde36b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:47 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde3ce0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:47 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde27e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:48 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde8980>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:49 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde8710>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:49 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde9640>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:50 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde9d90>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:51 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde3830>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:51 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde1af0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:52 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde30e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:53 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde32c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:53 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde37d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:54 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde13a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:55 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde2240>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:55 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde2210>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:56 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde2c60>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:57 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde8230>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:57 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde8530>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:58 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde83e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:59 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde9040>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:30:59 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde2330>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:00 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde0260>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:01 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde06e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:01 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde10a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:02 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde3380>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:03 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde3d10>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:03 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde3e00>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:04 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde2f30>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:05 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde3830>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:05 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde95b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:06 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde84d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:07 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde9760>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:07 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde8aa0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:08 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde3f80>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:09 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde27e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:09 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde03b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:10 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde2c00>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:11 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde2e70>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:11 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde0f50>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:12 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde2ba0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:13 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde0f80>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:13 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fe013cb230>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:14 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde8620>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:15 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde8470>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:15 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde8bf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:16 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffdea420>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:17 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde2b40>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:17 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /register.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde22a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:18 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /register.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde2060>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:19 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /register.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde3350>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:19 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /register.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde2db0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:20 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /register.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde3560>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:21 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /register.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde36b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:21 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /register.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde2690>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:22 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /register.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffdea1b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:23 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /register.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde9130>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:23 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /register.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde8350>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:24 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /register.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde85f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:25 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /register.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffdea7b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:25 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /register.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde36e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:26 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /register.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde3200>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:27 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /register.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde3260>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:27 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /register.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde1790>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:28 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /register.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde20f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:29 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /register.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde0380>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:29 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /register.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde14c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:30 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /register.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde08c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:31 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /register.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffdeaa20>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:31 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /register.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde9730>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:32 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /register.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde8470>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:33 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /register.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffdea5d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:33 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /register.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffdeacc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:34 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /register.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde1460>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:35 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /register.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde2180>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:35 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /register.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde0f50>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:36 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /register.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde2e70>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:37 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /register.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde2c00>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:37 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /register (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde31a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:38 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /register (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde26f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:39 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /register (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde2a20>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:39 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /register (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde8110>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:40 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /register (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde9160>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:41 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /register (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde80e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:41 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /user.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffdea8a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:42 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /user.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffdeb110>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:43 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /user.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde2f30>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:43 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /user.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde3440>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:44 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /user.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde2ea0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:45 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /user.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde3350>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:45 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /user.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde3500>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:46 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /user.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde1100>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:47 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /user.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde37a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:47 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /user.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde2b40>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:48 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /user.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde83b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:49 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /user.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde8200>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:49 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /user.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde8080>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:50 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /user.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffdea630>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:51 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /user.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffdeb5c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:51 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /user.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde2b40>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:52 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /user.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde1520>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:53 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /user.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde2750>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:53 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /user.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde0ec0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:54 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /user.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde34d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:55 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /user.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde11f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:55 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /user.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde3200>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:56 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /user.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde26c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:57 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /user.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde8b90>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:57 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /user.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffdea0c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:58 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /user.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde8710>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:59 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /user.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde8a40>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:31:59 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /user.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffdeba70>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:00 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /user.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde24b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:01 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /user.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde3a70>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:01 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /user (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde1670>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:02 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /user (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde0620>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:03 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /user (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde3500>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:03 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /user (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde1040>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:04 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /user (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde12b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:05 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /user (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffdeb200>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:05 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /users.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde80e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:06 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /users.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde8170>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:07 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /users.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde8b90>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:07 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /users.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffdebdd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:08 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /users.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffe40200>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:09 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /users.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffdebe60>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:09 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /users.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffdeb2f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:10 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /users.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde8590>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:11 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /users.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde9760>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:11 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /users.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde2030>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:12 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /users.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde1460>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:13 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /users.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde1040>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:13 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /users.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde2570>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:14 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /users.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde33b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:15 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /users.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde11f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:15 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /users.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde3a40>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:16 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /users.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde3e30>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:17 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /users.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffe40440>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:17 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /users.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde1070>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:18 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /users.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde3d70>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:19 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /users.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde38f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:19 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /users.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde3080>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:20 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /users.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde2060>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:21 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /users.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde3650>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:21 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /users.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde25d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:22 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /users.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffdea780>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:23 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /users.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffdea8a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:23 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /users.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde91f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:24 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /users.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffdea030>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:25 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /users.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffdeb830>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:25 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /users (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffe40aa0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:26 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /users (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde25a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:27 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /users (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde37d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:27 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /users (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde2060>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:28 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /users (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde34d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:29 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /users (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde3bf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:29 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /profile.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde2ff0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:30 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /profile.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde2cf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:31 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /profile.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffdebc80>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:31 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /profile.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffdeb2f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:32 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /profile.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde8590>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:33 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /profile.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde82f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:33 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /profile.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffdeae40>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:34 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /profile.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffdebad0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:35 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /profile.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde2cf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:35 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /profile.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde14c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:36 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /profile.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde3530>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:37 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /profile.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde16a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:37 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /profile.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde0680>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:38 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /profile.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde12b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:39 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /profile.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde25d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:39 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /profile.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffdebb00>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:40 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /profile.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffdeb980>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:41 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /profile.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde8a10>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:41 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /profile.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde9f40>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:42 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /profile.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde8080>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:43 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /profile.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde87d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:43 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /profile.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffdeb110>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:44 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /profile.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde3710>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:45 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /profile.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde2210>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:45 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /profile.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde2540>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:46 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /profile.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde1640>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:47 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /profile.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde12e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:47 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /profile.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde3410>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:48 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /profile.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde2ff0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:49 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /profile.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffdeaed0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:49 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /profile (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffdebef0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:50 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /profile (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffdeb2f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:51 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /profile (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffdeae10>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:51 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /profile (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffdeb9e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:52 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /profile (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde96a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:53 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /profile (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde3230>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:53 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /search.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde3a40>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:54 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /search.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde2ab0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:55 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /search.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde0fe0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:55 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /search.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde1790>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:56 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /search.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde1190>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:57 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /search.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde22d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:57 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /search.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde0ef0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:58 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /search.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde8620>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:59 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /search.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffdea0c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:32:59 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /search.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffdeb6b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:00 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /search.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffdebc50>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:01 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /search.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffdebd40>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:01 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /search.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffdeadb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:02 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /search.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde00e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:03 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /search.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde1910>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:03 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /search.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde2270>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:04 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /search.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde0f50>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:05 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /search.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde33b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:05 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /search.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79fdffde34d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:10 - root - INFO - Logging enabled to file: scanner.log
2025-05-08 12:33:10 - __main__ - INFO - Initializing SQL Injection Scanner...
2025-05-08 12:33:10 - __main__ - INFO - Loaded 37 unique payloads from data/payloads.txt
2025-05-08 12:33:10 - __main__ - INFO - Attempting login to http://localhost:8000/process.php with method POST
2025-05-08 12:33:10 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /process.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b0d9a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:11 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /process.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b0dbb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:12 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /process.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b0e0f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:12 - __main__ - WARNING - Login request to http://localhost:8000/process.php failed (no response).
2025-05-08 12:33:12 - __main__ - INFO - Scanner initialized. Base scan URL set to: http://localhost:8000/
2025-05-08 12:33:12 - __main__ - INFO - Starting discovery from base: http://localhost:8000/ using wordlist: data/common_paths.txt
2025-05-08 12:33:12 - __main__ - INFO - Generated 228 potential targets for discovery.
2025-05-08 12:33:12 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b0e900>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:13 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b0f080>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:14 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b0f350>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:14 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b0ea20>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:15 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b0e9c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:16 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b0e1e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:16 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b0de20>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:17 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b0f560>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:18 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b0f950>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:18 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b0fa40>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:19 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b24d10>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:20 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b24170>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:20 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b24a40>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:21 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b24c50>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:22 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b25310>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:22 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b25640>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:23 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b0fe60>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:24 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b0fe30>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:24 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b0f7d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:25 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b0dcd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:26 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b0e870>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:26 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b0ef30>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:27 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b0ea20>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:28 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b25370>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:28 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b24f50>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:29 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b24650>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:30 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b24560>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:30 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b25ac0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:31 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b26060>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:32 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b0df70>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:32 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b0dee0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:33 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b0df10>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:34 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b0f770>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:34 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b0fa40>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:35 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b0fe60>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:36 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /admin (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b25a60>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:36 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b24200>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:37 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b242c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:38 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b24860>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:38 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b25280>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:39 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b26270>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:40 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b265a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:40 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b0fad0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:41 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b0fdd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:42 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b0dcd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:42 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b0dd60>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:43 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b0f020>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:44 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b0ed50>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:44 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b26870>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:45 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b26180>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:46 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b254c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:46 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b24950>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:47 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b24890>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:48 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b241a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:48 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b26960>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:49 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b0f3b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:50 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b0da90>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:50 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b0db80>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:51 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b0dfd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:52 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b0da60>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:52 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b0fbf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:53 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b0f200>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:54 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b24a40>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:54 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b24d40>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:55 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b24ec0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:56 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b24fb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:56 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b25490>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:57 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b25ca0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:58 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b0de20>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:58 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b0f890>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:33:59 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b0f6e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:34:00 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /administrator (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b0ddc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:34:00 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b0db20>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:34:01 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b0f680>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:34:02 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b0f3b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:34:02 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b262d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:34:03 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b25280>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:34:04 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b24f20>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:34:04 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b25be0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:34:05 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b24110>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:34:06 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b25c10>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:34:06 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b0f0b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:34:07 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b0e030>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:34:08 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b0ef30>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:34:08 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b0ee70>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:34:09 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b0f6e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:34:10 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b0fad0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:34:10 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b0f3e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:34:11 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b25b50>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:34:12 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b25a90>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:34:12 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b24740>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:34:13 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b25040>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:34:14 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b25100>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:34:14 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b25610>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:34:15 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b0f3e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:34:16 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login.bak (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b0ff80>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:34:16 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b0fec0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:34:17 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b0ee70>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:34:18 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b0d190>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:34:18 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b0dbb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:34:19 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b0ef60>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:34:20 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login.old (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b25f10>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:34:20 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b24f50>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:34:21 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b24980>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:34:22 - src.http_client - ERROR - Attempt 3 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b24200>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:34:22 - src.http_client - ERROR - Attempt 1 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b245c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-08 12:34:23 - src.http_client - ERROR - Attempt 2 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c9e75b26f00>: Failed to establish a new connection: [Errno 111] Connection refused'))
